### ISSUE TITLE
CSM Fails to compile in Fuerte branch

### ISSUE THREAD

**Issue by martimorta** [ccny-ros-pkg/scan_tools#12]
Hi, trying to compile csm in fuerte we bumped into the following error, is there a way to fix it? Thanks!

```
[ rosmake ] All 28 linessm: 64.3 sec ]                                                     [ 1 Active 40/42 Complete ]
{-------------------------------------------------------------------------------
  mkdir -p build
  if [ ! -f csm-git-23703a998fff57250322.tar.gz.md5sum ]; then echo "Error: Couldn't find md5sum file csm-git-23703a998fff57250322.tar.gz.md5sum" && false; fi
  `rospack find rosbuild`/bin/download_checkmd5.py https://code.ros.org/svn/release/download/thirdparty/csm-git-23703a998fff57250322.tar.gz build/csm-git-23703a998fff57250322.tar.gz `awk {'print $1'} csm-git-23703a998fff57250322.tar.gz.md5sum`
  [rosbuild] Downloading https://code.ros.org/svn/release/download/thirdparty/csm-git-23703a998fff57250322.tar.gz to build/csm-git-23703a998fff57250322.tar.gz...Traceback (most recent call last):
    File "/opt/ros/fuerte/share/ros/core/rosbuild/bin/download_checkmd5.py", line 56, in <module>
      sys.exit(main())
    File "/opt/ros/fuerte/share/ros/core/rosbuild/bin/download_checkmd5.py", line 28, in main
      urllib.urlretrieve(uri, dest)
    File "/usr/lib/python2.7/urllib.py", line 93, in urlretrieve
      return _urlopener.retrieve(url, filename, reporthook, data)
    File "/usr/lib/python2.7/urllib.py", line 239, in retrieve
      fp = self.open(url, data)
    File "/usr/lib/python2.7/urllib.py", line 207, in open
      return getattr(self, name)(url)
    File "/usr/lib/python2.7/urllib.py", line 436, in open_https
      h.endheaders(data)
    File "/usr/lib/python2.7/httplib.py", line 954, in endheaders
      self._send_output(message_body)
    File "/usr/lib/python2.7/httplib.py", line 814, in _send_output
      self.send(msg)
    File "/usr/lib/python2.7/httplib.py", line 776, in send
      self.connect()
    File "/usr/lib/python2.7/httplib.py", line 1157, in connect
      self.timeout, self.source_address)
    File "/usr/lib/python2.7/socket.py", line 571, in create_connection
      raise err
  IOError: [Errno socket error] [Errno 110] Connection timed out
-------------------------------------------------------------------------------}
[ rosmake ] Output from build of package csm written to:
[ rosmake ]    /home/mmorta/.ros/rosmake/rosmake_output-20140303-174108/csm/build_output.log
[rosmake-0] Finished <<< csm [FAIL] [ 64.33 seconds ]
```

**Comment by joannystephant** [comment]
It is the case
you need to add 
csm/build/csm-git-23703a998fff57250322.tar.gz
extract
and redo rosmake install scan_tools
